# rename this config file to config.yaml in the same dir as the executable

log_level: debug

http:
  listen: 127.0.0.1:9000

themo:
  update_interval: 30m
  username: my_username
  password: my_password
